// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO3Herd2O5pIY2NpLuWk1Pw7NvUjV6NnM',
    appId: '1:891233203501:web:2d87e5dab4080e20fd0fa4',
    messagingSenderId: '891233203501',
    projectId: 'fasum-app-7839a',
    authDomain: 'fasum-app-7839a.firebaseapp.com',
    databaseURL: 'https://fasum-app-7839a-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-7839a.appspot.com',
    measurementId: 'G-5JPLF3QDR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPdF7kXtumgZnAe8DihqlX6Uqwj1JXbwU',
    appId: '1:891233203501:android:12ff24d522a5d6b8fd0fa4',
    messagingSenderId: '891233203501',
    projectId: 'fasum-app-7839a',
    databaseURL: 'https://fasum-app-7839a-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-7839a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxs9N23niTGzV6Vk-NXj4-7nb7sq1H2D0',
    appId: '1:891233203501:ios:fc743ae692ae0b94fd0fa4',
    messagingSenderId: '891233203501',
    projectId: 'fasum-app-7839a',
    databaseURL: 'https://fasum-app-7839a-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-7839a.appspot.com',
    androidClientId: '891233203501-b16lioubhvp8e1dom0mft8pn0u6jq323.apps.googleusercontent.com',
    iosClientId: '891233203501-g7s803apohntuvcef4oj3kfqf47uvegc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxs9N23niTGzV6Vk-NXj4-7nb7sq1H2D0',
    appId: '1:891233203501:ios:fc743ae692ae0b94fd0fa4',
    messagingSenderId: '891233203501',
    projectId: 'fasum-app-7839a',
    databaseURL: 'https://fasum-app-7839a-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-7839a.appspot.com',
    androidClientId: '891233203501-b16lioubhvp8e1dom0mft8pn0u6jq323.apps.googleusercontent.com',
    iosClientId: '891233203501-g7s803apohntuvcef4oj3kfqf47uvegc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO3Herd2O5pIY2NpLuWk1Pw7NvUjV6NnM',
    appId: '1:891233203501:web:a2e9b4c20849cbf7fd0fa4',
    messagingSenderId: '891233203501',
    projectId: 'fasum-app-7839a',
    authDomain: 'fasum-app-7839a.firebaseapp.com',
    databaseURL: 'https://fasum-app-7839a-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-7839a.appspot.com',
    measurementId: 'G-8EWX15KF99',
  );

}